name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Create release
        shell: bash
        run: |
          set -euo pipefail
          TAG="${GITHUB_REF_NAME}"
          if gh release view "$TAG" >/dev/null 2>&1; then
            echo "Release $TAG already exists. Skipping."
            exit 0
          fi
          EXTRA_FLAGS=()
          if [[ "$TAG" == *alpha* || "$TAG" == *beta* || "$TAG" == *rc* ]]; then
            EXTRA_FLAGS+=(--prerelease)
          fi
          gh release create "$TAG" --title "$TAG" --generate-notes "${EXTRA_FLAGS[@]}"
